language: java

before_deploy:
  - mvn versions:set -DnewVersion=${TRAVIS_TAG}
  - mvn clean package

deploy:
  provider: releases
  api_key:
    secure: ${SECURE_API_KEY}
  file: target/keycloak-admin-wrapper-${TRAVIS_TAG}.jar
  on:
    repo: kurzdigital/keycloak-admin-wrapper
  on:
    tags: true
