language: java

script:
  - mvn clean package

before_deploy:
  - echo $SECURE_GPG_KEY | base64 --decode > codesigning.asc.enc
  - openssl aes-256-cbc -K $encrypted_6f50ab553585_key -iv $encrypted_6f50ab553585_iv -in codesigning.asc.enc -out codesigning.asc -d
  - shred --remove codesigning.asc.enc
  - gpg --fast-import codesigning.asc
  - shred --remove codesigning.asc
  - mvn versions:set -DnewVersion=${TRAVIS_TAG}

deploy:
  provider: script
  script: mvn --settings .maven.xml -P sign clean deploy
  skip_cleanup: true
  on:
    tags: true

cache:
  directories:
    - ~/.m2/repository

#notifications:
#  email: false
#  slack:
#    secure:<some-key>
